contact_links:
  - name: ğŸ“¢ Telegram / ØªÙ„Ú¯Ø±Ø§Ù…
    url: https://t.me/hysteria2_panel
    about: Get help, discuss features, and connect with other users. / Ø¯Ø±ÛŒØ§ÙØª Ú©Ù…Ú©ØŒ Ø¨Ø­Ø« Ø¯Ø±Ø¨Ø§Ø±Ù‡ ÙˆÛŒÚ˜Ú¯ÛŒâ€ŒÙ‡Ø§ Ùˆ Ø§Ø±ØªØ¨Ø§Ø· Ø¨Ø§ Ø³Ø§ÛŒØ± Ú©Ø§Ø±Ø¨Ø±Ø§Ù†.
  - name: ğŸ“„ Project Documentation / Ù…Ø³ØªÙ†Ø¯Ø§Øª Ù¾Ø±ÙˆÚ˜Ù‡
    url: https://returnfi.github.io/Hys2-docs/
    about: Visit our documentation for more information. / Ø¨Ø±Ø§ÛŒ Ø§Ø·Ù„Ø§Ø¹Ø§Øª Ø¨ÛŒØ´ØªØ± Ù…Ø³ØªÙ†Ø¯Ø§Øª Ù¾Ø±ÙˆÚ˜Ù‡ Ø±Ø§ Ø¨Ø±Ø±Ø³ÛŒ Ú©Ù†ÛŒØ¯.
blank_issues_enabled: false
